id: PC9996A46
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ294727
  title: ཞི་བྱེད་དང་གཅོད་ཡུལ་སོགས་གདམས་ངག་ཐོར་བུའི་ཆོས་སྐོར།
  volumes:
    85a2617abfe44d4ca18243816f5b2145:
      image_group_id: I8LS24006
      title: ''
      base_file: v001.txt
  author: ''
