id: I1169CC46
legacy_id: PC9996A46
ocr_import_info:
  bdrc_scan_id: W4CZ294727
  source: bdrc
  ocr_info:
    timestamp: '2022-03-26T09:42:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T18:30:00.149602+00:00'
last_modified: 2022-09-04 02:30:22.459791
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ294727
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ294727
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཞི་བྱེད་དང་གཅོད་ཡུལ་སོགས་གདམས་ངག་ཐོར་བུའི་ཆོས་སྐོར།
statistics:
  ocr_word_mean_confidence_index: 0.9780021570384773
  ocr_word_median_confidence_index: 0.99
quality: null
bases:
  I8LS24006:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS24006
      total_pages: 402
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS24006.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9780021570384773
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
